services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homegantry-ui
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: homegantry-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For monitoring other containers
    restart: unless-stopped
